# Generated by Django 4.1.4 on 2022-12-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_livro_capa"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioAdmin",
            fields=[
                (
                    "autor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.autor",
                    ),
                ),
            ],
            bases=("core.autor",),
        ),
    ]
