# Generated by Django 4.1.3 on 2022-12-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_autor_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='core.autor'),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.editora'),
            preserve_default=False,
        ),
    ]
